server:
  port: 10010

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1

            - id: exam-service
              uri: lb://exam-service
              predicates:
                - Path=/exam-service/**
              filters:
                - StripPrefix=1
                - name: AuthFilterFactory
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 12345678