server:
  port: 10010

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**

            - id: exam-service
              uri: lb://exam-service
              predicates:
                - Path=/exam-service/**
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 12345678